import Foundation

// 环境切换器 - 支持global和per-project两种模式
class EnvironmentSwitcher: ObservableObject {
    static let shared = EnvironmentSwitcher()
    
    enum SwitchMode {
        case global         // 全局切换，影响整个用户环境
        case project        // 项目级切换，仅影响特定项目目录
    }
    
    enum ConfigFormat {
        case asdfToolVersions   // .tool-versions 格式（asdf标准）
        case direnv            // .envrc 格式（direnv兼容）
        case shellScript       // shell脚本格式
    }
    
    private init() {}
    
    // MARK: - Global Environment Switching
    
    /// 全局切换环境版本
    func switchGlobalEnvironment(versions: [String: String]) -> (Bool, String) {
        var logs = "🔄 正在切换全局环境...\n\n"
        var success = true
        
        for (tool, version) in versions {
            let result = switchGlobalTool(tool: tool, version: version)
            logs += result.1
            if !result.0 {
                success = false
            }
        }
        
        // 刷新shims
        let reshimResult = Shell.run("asdf reshim")
        if reshimResult.code == 0 {
            logs += "\n✅ 已刷新所有工具的shims\n"
        } else {
            logs += "\n⚠️ 刷新shims时出现警告: \(reshimResult.err)\n"
        }
        
        // 更新shell配置
        updateShellConfiguration(versions: versions)
        
        logs += success ? "\n🎉 全局环境切换完成！" : "\n❌ 全局环境切换过程中出现错误"
        return (success, logs)
    }
    
    /// 切换单个工具的全局版本
    private func switchGlobalTool(tool: String, version: String) -> (Bool, String) {
        // 检查版本是否已安装
        let checkResult = Shell.run("asdf list \(tool) | grep -q '\(version)' && echo 'installed' || echo 'not-installed'")
        
        if checkResult.out.contains("not-installed") {
            // 尝试安装版本
            let installResult = Shell.run("asdf install \(tool) \(version)")
            if installResult.code != 0 {
                return (false, "❌ [\(tool)] 安装版本 \(version) 失败: \(installResult.err)\n")
            }
        }
        
        // 设置全局版本
        let setResult = Shell.run("asdf global \(tool) \(version)")
        if setResult.code == 0 {
            return (true, "✅ [\(tool)] 已切换到版本 \(version)\n")
        } else {
            return (false, "❌ [\(tool)] 切换到版本 \(version) 失败: \(setResult.err)\n")
        }
    }
    
    // MARK: - Project-Level Environment Switching
    
    /// 为项目目录设置本地环境
    func setupProjectEnvironment(projectPath: String, versions: [String: String], format: ConfigFormat = .asdfToolVersions) -> (Bool, String) {
        let projectURL = URL(fileURLWithPath: projectPath)
        var logs = "📁 正在为项目设置本地环境: \(projectPath)\n\n"
        
        switch format {
        case .asdfToolVersions:
            let result = createToolVersionsFile(projectURL: projectURL, versions: versions)
            logs += result.1
            return (result.0, logs)
            
        case .direnv:
            let result = createEnvrcFile(projectURL: projectURL, versions: versions)
            logs += result.1
            return (result.0, logs)
            
        case .shellScript:
            let result = createShellScriptConfig(projectURL: projectURL, versions: versions)
            logs += result.1
            return (result.0, logs)
        }
    }
    
    /// 创建 .tool-versions 文件（asdf标准格式）
    private func createToolVersionsFile(projectURL: URL, versions: [String: String]) -> (Bool, String) {
        let toolVersionsURL = projectURL.appendingPathComponent(".tool-versions")
        var content = "# asdf tool versions\n# Generated by MacEnvSwitcher on \(Date())\n\n"
        
        for (tool, version) in versions.sorted(by: { $0.key < $1.key }) {
            content += "\(tool) \(version)\n"
        }
        
        do {
            try content.write(to: toolVersionsURL, atomically: true, encoding: .utf8)
            return (true, "✅ 已创建 .tool-versions 文件\n   路径: \(toolVersionsURL.path)\n")
        } catch {
            return (false, "❌ 创建 .tool-versions 文件失败: \(error.localizedDescription)\n")
        }
    }
    
    /// 创建 .envrc 文件（direnv格式）
    private func createEnvrcFile(projectURL: URL, versions: [String: String]) -> (Bool, String) {
        let envrcURL = projectURL.appendingPathComponent(".envrc")
        var content = """
        #!/bin/bash
        # direnv configuration
        # Generated by MacEnvSwitcher on \(Date())
        
        # Load asdf environment
        if command -v asdf >/dev/null 2>&1; then
            source "$(brew --prefix asdf)/libexec/asdf.sh" 2>/dev/null || true
        fi
        
        # Set tool versions
        """
        
        for (tool, version) in versions.sorted(by: { $0.key < $1.key }) {
            content += """
            
            # \(tool.capitalized) \(version)
            if command -v asdf >/dev/null 2>&1; then
                if asdf list \(tool) | grep -q '\(version)'; then
                    export ASDF_\(tool.uppercased())_VERSION=\(version)
                    asdf local \(tool) \(version) 2>/dev/null || true
                else
                    echo "Warning: \(tool) version \(version) not installed"
                fi
            fi
            """
        }
        
        content += """
        
        
        # Allow direnv to reload when this file changes
        watch_file .envrc
        """
        
        do {
            try content.write(to: envrcURL, atomically: true, encoding: .utf8)
            // 使文件可执行
            _ = Shell.run("chmod +x '\(envrcURL.path)'")
            return (true, "✅ 已创建 .envrc 文件\n   路径: \(envrcURL.path)\n   💡 提示: 运行 'direnv allow' 来激活配置\n")
        } catch {
            return (false, "❌ 创建 .envrc 文件失败: \(error.localizedDescription)\n")
        }
    }
    
    /// 创建shell脚本配置
    private func createShellScriptConfig(projectURL: URL, versions: [String: String]) -> (Bool, String) {
        let scriptURL = projectURL.appendingPathComponent("setup-env.sh")
        var content = """
        #!/bin/bash
        # Environment setup script
        # Generated by MacEnvSwitcher on \(Date())
        # Usage: source setup-env.sh
        
        echo "🔧 Setting up development environment..."
        
        # Check if asdf is available
        if ! command -v asdf >/dev/null 2>&1; then
            echo "❌ asdf not found. Please install asdf first."
            return 1
        fi
        
        # Source asdf
        ASDF_SH=$(brew --prefix asdf 2>/dev/null)/libexec/asdf.sh
        if [ -f "$ASDF_SH" ]; then
            source "$ASDF_SH"
        fi
        
        """
        
        for (tool, version) in versions.sorted(by: { $0.key < $1.key }) {
            content += """
            
            # Setup \(tool.capitalized) \(version)
            echo "📦 Setting up \(tool) \(version)..."
            if asdf list \(tool) | grep -q '\(version)'; then
                asdf local \(tool) \(version)
                echo "✅ \(tool.capitalized) \(version) activated"
            else
                echo "⚠️  \(tool.capitalized) \(version) not installed. Installing..."
                asdf install \(tool) \(version) && asdf local \(tool) \(version)
            fi
            """
        }
        
        content += """
        
        
        echo "🎉 Environment setup complete!"
        echo "Current tool versions:"
        """
        
        for tool in versions.keys.sorted() {
            content += """
            echo "  \(tool): $(asdf current \(tool) 2>/dev/null | awk '{print $2}' || echo 'not set')"
            """
        }
        
        do {
            try content.write(to: scriptURL, atomically: true, encoding: .utf8)
            // 使文件可执行
            _ = Shell.run("chmod +x '\(scriptURL.path)'")
            return (true, "✅ 已创建环境设置脚本\n   路径: \(scriptURL.path)\n   💡 使用方法: source setup-env.sh\n")
        } catch {
            return (false, "❌ 创建环境脚本失败: \(error.localizedDescription)\n")
        }
    }
    
    // MARK: - Environment Detection and Management
    
    /// 检测项目的当前环境配置
    func detectProjectEnvironment(projectPath: String) -> [String: Any] {
        let projectURL = URL(fileURLWithPath: projectPath)
        var detected: [String: Any] = [:]
        
        // 检查 .tool-versions
        let toolVersionsURL = projectURL.appendingPathComponent(".tool-versions")
        if FileManager.default.fileExists(atPath: toolVersionsURL.path) {
            detected["tool_versions"] = parseToolVersionsFile(url: toolVersionsURL)
        }
        
        // 检查 .envrc
        let envrcURL = projectURL.appendingPathComponent(".envrc")
        if FileManager.default.fileExists(atPath: envrcURL.path) {
            detected["envrc"] = true
        }
        
        // 检查 setup-env.sh
        let setupScriptURL = projectURL.appendingPathComponent("setup-env.sh")
        if FileManager.default.fileExists(atPath: setupScriptURL.path) {
            detected["setup_script"] = true
        }
        
        // 检查其他常见配置文件
        let commonConfigs = [
            "package.json": "nodejs",
            "Gemfile": "ruby", 
            "requirements.txt": "python",
            "go.mod": "golang",
            "pom.xml": "java",
            "build.gradle": "java",
            "Cargo.toml": "rust"
        ]
        
        var projectLanguages: [String] = []
        for (file, language) in commonConfigs {
            let fileURL = projectURL.appendingPathComponent(file)
            if FileManager.default.fileExists(atPath: fileURL.path) {
                projectLanguages.append(language)
            }
        }
        
        detected["detected_languages"] = projectLanguages
        
        return detected
    }
    
    /// 解析 .tool-versions 文件
    private func parseToolVersionsFile(url: URL) -> [String: String] {
        guard let content = try? String(contentsOf: url) else { return [:] }
        
        var versions: [String: String] = [:]
        
        for line in content.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            
            // 跳过空行和注释
            if trimmed.isEmpty || trimmed.hasPrefix("#") {
                continue
            }
            
            let components = trimmed.components(separatedBy: .whitespaces)
            if components.count >= 2 {
                let tool = components[0]
                let version = components[1]
                versions[tool] = version
            }
        }
        
        return versions
    }
    
    /// 获取当前全局环境配置
    func getCurrentGlobalEnvironment() -> [String: String] {
        let tools = ["nodejs", "python", "ruby", "java", "golang", "rust", "gradle", "maven"]
        var current: [String: String] = [:]
        
        for tool in tools {
            let result = Shell.run("asdf current \(tool) 2>/dev/null")
            if result.code == 0 && !result.out.isEmpty {
                let components = result.out.trimmingCharacters(in: .whitespacesAndNewlines).components(separatedBy: .whitespaces)
                if components.count >= 2 {
                    current[tool] = components[1]
                }
            }
        }
        
        return current
    }
    
    // MARK: - Shell Integration
    
    /// 更新shell配置以支持环境切换
    private func updateShellConfiguration(versions: [String: String]) {
        let shellConfigFiles = ["~/.zshrc", "~/.bashrc", "~/.bash_profile"]
        
        for configFile in shellConfigFiles {
            let expandedPath = NSString(string: configFile).expandingTildeInPath
            if FileManager.default.fileExists(atPath: expandedPath) {
                updateShellConfigFile(path: expandedPath, versions: versions)
            }
        }
    }
    
    /// 更新单个shell配置文件
    private func updateShellConfigFile(path: String, versions: [String: String]) {
        guard let content = try? String(contentsOfFile: path) else { return }
        
        var newContent = content
        let marker = "# MacEnvSwitcher managed section"
        let endMarker = "# End MacEnvSwitcher section"
        
        // 移除旧的MacEnvSwitcher配置段
        if let startRange = newContent.range(of: marker),
           let endRange = newContent.range(of: endMarker) {
            let rangeToRemove = startRange.lowerBound..<endRange.upperBound
            newContent.removeSubrange(rangeToRemove)
            newContent = newContent.trimmingCharacters(in: .whitespacesAndNewlines)
        }
        
        // 添加新的配置段
        var configSection = "\n\n\(marker)\n"
        configSection += "# Auto-generated environment configuration\n"
        configSection += "# Last updated: \(Date())\n\n"
        
        // 添加asdf初始化
        configSection += "# Initialize asdf\n"
        configSection += "if command -v asdf >/dev/null 2>&1; then\n"
        configSection += "    ASDF_SH=$(brew --prefix asdf 2>/dev/null)/libexec/asdf.sh\n"
        configSection += "    [ -f \"$ASDF_SH\" ] && source \"$ASDF_SH\"\n"
        configSection += "fi\n\n"
        
        // 添加环境变量
        for (tool, version) in versions {
            if tool == "java" {
                configSection += "# Java environment\n"
                configSection += "export JAVA_HOME=\"$(asdf where java \(version) 2>/dev/null || echo '')\"\n"
                configSection += "[ -n \"$JAVA_HOME\" ] && export PATH=\"$JAVA_HOME/bin:$PATH\"\n\n"
            }
        }
        
        configSection += "\(endMarker)\n"
        
        newContent += configSection
        
        // 写回文件
        try? newContent.write(toFile: path, atomically: true, encoding: .utf8)
    }
    
    // MARK: - Project Template Generation
    
    /// 为特定项目类型生成推荐的环境配置
    func generateProjectTemplate(projectType: String) -> [String: String] {
        switch projectType.lowercased() {
        case "ios", "swift":
            return [
                "ruby": "3.2.0",    // For CocoaPods, Fastlane
                "nodejs": "18.17.0"  // For React Native components
            ]
            
        case "android":
            return [
                "java": "17.0.2",
                "gradle": "8.4",
                "nodejs": "18.17.0"
            ]
            
        case "web", "frontend", "javascript", "typescript":
            return [
                "nodejs": "20.9.0",
                "python": "3.11.0"  // For build tools
            ]
            
        case "python", "django", "flask":
            return [
                "python": "3.11.6",
                "nodejs": "18.17.0"  // For frontend assets
            ]
            
        case "ruby", "rails":
            return [
                "ruby": "3.2.0",
                "nodejs": "18.17.0"  // For Webpacker/asset pipeline
            ]
            
        case "java", "spring":
            return [
                "java": "17.0.2",
                "gradle": "8.4",
                "maven": "3.9.4"
            ]
            
        case "go", "golang":
            return [
                "golang": "1.21.4"
            ]
            
        case "rust":
            return [
                "rust": "1.74.0"
            ]
            
        case "data-science", "ml":
            return [
                "python": "3.11.6",
                "nodejs": "18.17.0",  // For Jupyter extensions
                "rust": "1.74.0"      // For performance-critical components
            ]
            
        default:
            return [
                "nodejs": "20.9.0",
                "python": "3.11.6",
                "ruby": "3.2.0",
                "java": "17.0.2"
            ]
        }
    }
    
    /// 为已有项目生成智能环境建议
    func suggestEnvironmentForProject(projectPath: String) -> [String: String] {
        let detected = detectProjectEnvironment(projectPath: projectPath)
        guard let languages = detected["detected_languages"] as? [String] else {
            return generateProjectTemplate(projectType: "general")
        }
        
        var suggested: [String: String] = [:]
        
        for language in languages {
            let template = generateProjectTemplate(projectType: language)
            for (tool, version) in template {
                suggested[tool] = version
            }
        }
        
        return suggested.isEmpty ? generateProjectTemplate(projectType: "general") : suggested
    }
}